In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [14]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

# AND Operation:

In [15]:

data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [16]:
X = AND.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [19]:
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [20]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [-6.02428009e-05  1.24735490e-04 -4.42004942e-06]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 0 1]
error: 
0   -1
1   -1
2    0
3    0
Name: y, dtype: int64
updated weights: 
[-6.02428009e-05 -4.99875265e-01  9.99995580e-01]
#############

for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[4.99939757e-01 1.24735490e-04 4.99995580e-01]
#############

for epoch: 2
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[4.99939757e-01 1.24735490e-04 4.99995580e-01]
#############

for epoch: 3
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[4.99939757e-01 1.24735490e-04 4.99995580e-01]
#############

for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[4.99939757e-01 1.2473549

In [23]:
model.predict(X)

array([0, 0, 0, 1])

In [24]:
model.weights

array([4.99939757e-01, 1.24735490e-04, 4.99995580e-01])